using System.Text;

namespace DiskWeaver.Executor;

/// <summary>
/// Emits a bash script that creates sparse-file-backed loop devices for
/// validating generated scripts safely (see docs/testing.md), one per
/// given size.
/// </summary>
public static class LoopDeviceScriptEmitter
{
    public static string Render(IReadOnlyList<long> sizesBytes, string workDir = "~/diskweaver-test")
    {
        var script = new StringBuilder();
        Line(script, "#!/usr/bin/env bash");
        Line(script, "set -euo pipefail");
        Line(script);
        Line(script, "# Generated by `diskweaver testkit`. Creates sparse-file-backed loop devices");
        Line(script, "# for safely validating a generated pool-build script. See docs/testing.md.");
        Line(script);
        Line(script, $"mkdir -p {workDir}");
        Line(script, $"cd {workDir}");
        Line(script);

        for (var i = 0; i < sizesBytes.Count; i++)
        {
            Line(script, $"truncate -s {sizesBytes[i]} disk{i}.img");
        }

        Line(script);
        Line(script, "declare -A DEV");
        for (var i = 0; i < sizesBytes.Count; i++)
        {
            // -P scans for partitions after parted writes a table; without it, loopNpM
            // device nodes never appear and mdadm/pvcreate can't find them.
            Line(script, $"DEV[{i}]=$(sudo losetup -fP --show disk{i}.img)");
        }

        Line(script);
        Line(script, "for i in \"${!DEV[@]}\"; do echo \"disk$i.img -> ${DEV[$i]}\"; done");
        Line(script);
        Line(script, "# Scoped to ONLY these loop devices -- do not switch this to a system-wide");
        Line(script, "# `lsblk` capture, or your real disks will end up in the same plan/script.");
        // No -d, and FSTYPE/MOUNTPOINTS included: LsblkOutputParser now refuses any capture missing
        // those columns (it can't otherwise tell "confirmed blank" from "never checked"), and -d
        // would hide partitions/holders that the eligibility check needs to see.
        Line(script, "lsblk --json -b -o NAME,SIZE,TYPE,ID-LINK,FSTYPE,MOUNTPOINTS \"${DEV[@]}\" > inventory.json");
        Line(script, "echo \"Wrote inventory.json scoped to: ${DEV[*]}\"");

        return script.ToString();
    }

    // The generated script always runs on Linux, regardless of which OS DiskWeaver itself
    // runs on -- so lines are terminated with a plain '\n', never StringBuilder.AppendLine()'s
    // platform-dependent Environment.NewLine (which is "\r\n" when this runs on Windows, e.g.
    // the CLI during development). A CRLF-terminated script breaks `set -o pipefail` parsing
    // on real bash.
    private static void Line(StringBuilder sb, string text = "") => sb.Append(text).Append('\n');
}
