using System.Text;

namespace DiskWeaver.Executor;

/// <summary>Renders an <see cref="ExecutionPlan"/> as a reviewable, human-readable bash script.</summary>
public static class ShellScriptEmitter
{
    public static string Render(ExecutionPlan plan)
    {
        // The generated script always runs on Linux, regardless of which OS DiskWeaver
        // itself runs on -- so lines are terminated with a plain '\n', never
        // StringBuilder.AppendLine()'s platform-dependent Environment.NewLine (which is
        // "\r\n" when this runs on Windows, e.g. the CLI during development). A
        // CRLF-terminated script breaks `set -o pipefail` parsing on real bash.
        var script = new StringBuilder();
        script.Append("#!/usr/bin/env bash\n");
        script.Append("set -euo pipefail\n");
        script.Append('\n');
        script.Append("# Generated by DiskWeaver. Review before running.\n");

        foreach (var step in plan.Steps)
        {
            script.Append('\n');
            script.Append($"# {step.Description}\n");

            if (step.Command is null)
            {
                continue;
            }

            script.Append(step.Command);
            foreach (var arg in step.Arguments)
            {
                script.Append(' ').Append(Quote(arg));
            }

            script.Append('\n');
        }

        return script.ToString();
    }

    private static string Quote(string arg)
    {
        return arg.Length > 0 && arg.All(c => char.IsLetterOrDigit(c) || c is '/' or '.' or '-' or '_' or '=' or '%')
            ? arg
            : "'" + arg.Replace("'", "'\\''") + "'";
    }
}
